---
title: "Email - C5.0 tree"
author: "Chloe Li"
date: "September 27, 2016"
output:
  pdf_document:
    highlight: monochrome
  html_document:
    highlight: pygments
    theme: united
  

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r load, echo=FALSE, message=FALSE, warning=FALSE}
#--------------------------------------------------------PREPARATION---------------------------------------------------------------#

              #clear environment if neccessary
              rm(list = ls())
              
              #load neccessary packages
              #Note, you might need to install pacman first
              pacman::p_load("party","ggplot2", "dplyr", "caret",
                             "reshape2","data.table","lme4","lattice","plyr",
                             "knitr", "cluster","grid","gridExtra","C50","e1071","partykit")
              
              #set your working directory
              setwd("~/Documents/02. EmailPrediction_CL/019.Email_C50_CL/")
              
              source("./dtTransform_FUN.R") #trasnform data type #don't change
              
              #grep data insert data name
              DT <- read.csv("./Data/eRFM_email_test1.csv")
              #str(DT)
              DT <- dtTransform(DT) #run this only once

#--------------------------------------------------------EDIT PART---------------------------------------------------------------#


            #setup independent variabe and dependent variable, create a formula, setup partition percentage
            #make sure the name of column names match
            percentPartition <- 0.75 #% of train set for partitioning
            IV <- c("Ro", "Rc","Fc","Fo","conversions", "lifetime_sent","clusterNum")
            DV <- "opened"
            trialsNum <- 1 #an integer specifying the number of boosting iterations. A value of one indicates that a single model is used.
            rules <- FALSE #whether wants to get a ruleset tree or none rule set. Rule set might provide clearer logic

#--------------------------------------------------------EDIT END---------------------------------------------------------------#
#--------------------------------------------------------RUN AUTO---------------------------------------------------------------#
            source("./C50_Model_FUN.R")
            
            C50_Model(DT, percentPartition,DV,IV,trialsNum,rules)

```